### ISSUE TITLE
Mixed-effects models or meta-regression using the median of medians approach? 

### ISSUE THREAD

**Issue by TACdeVries** [stmcg/metamedian#1]
Dear McGrath, 

My team and I are currently working on a meta-analysis on drug levels of a specific group of drugs, and we are seeking to pool certain percentile of drug levels as reported in multiple primary studies. For this purpose, we had decided to use the median of medians approach as reported in one of your papers given the distribution of these drugs levels are right-skewed. 

We want to explore heterogeneity in the effect by performing a sensitivity analyses on the effect of our risk of bias assessment. Is is possible to perform a mixed-effects model with the median of medians methods? 

For instance, using the methods as specified here: https://www.metafor-project.org/doku.php/tips:comp_two_independent_estimates ?

My expectation is that it is not possible, as you reported that formal heterogeneity analyses cannot be performing using these methods, but I wanted to ascertain this before continuing.  

Thank you so much for your time.

Kind regards,
Tim

**Comment by stmcg** [comment]
Hi Tim,

Thanks for the message. That's right -- the median of medians method can't be applied in a mixed effects model as you describe. Do the primary studies report other summary measures of the outcome besides the median (e.g., the first and third quartiles, the minimum and maximum values)? If so, there are other approaches in the `metamedian` package that can perform the types of analyses you describe.

Best,
Sean

**Comment by TACdeVries** [comment]
Dear Sean,

Thank you so much for responding so quickly. The outcome of interest for this particular set of meta-analyses is the 10th percentile value (and later also the 90th percentile). Thus, multiple studies report a 10th percentile value of drug levels and we want to pool those values to get a single pooled P10. 

We decided to go for the (unweighted) median of medians approach for this one as we thought it would be the most appropriate method. Do you have any thoughts on this? 

PS: We have also planned to perform meta-analyses for the median levels in these studies, and we decided to use the QE-method for that one. We have not yet decided on whether doing the described sensitivity analyses is worthwhile for the medians given our specific purpose.

Thank so much for taking the time to respond. Really appreciate it. 
Tim

**Comment by stmcg** [comment]
Hi Tim,

Thanks for the clarifications. Interesting questions! Would you mind if we continue our discussion by email (as it's starting to deviate from the `metamedian` package)? My email address is sean_mcgrath@g.harvard.edu

Best,
Sean

**Comment by TACdeVries** [comment]
Dear Sean,

Of course, very understandable. I will send you an email shortly.

Thanks,
Tim
