### ISSUE TITLE
Presentation of forestplot in metamedian

### ISSUE THREAD

**Issue by Emanuel-1986** [stmcg/metamedian#3]
Hi,

I am experimenting with the metamedian package for conducting meta-analysis of differences of medians.
I am using the dat.age dataset and I have managed to construct the forest plot below using this code:

> str(dat.asat)
> abc=metamedian(data=dat.age, median_method="qe")
> abc
> weights(abc)
> round(weights(abc, type="matrix"), 4)
> sav=forest(abc, order="obs", header=c("Study", "Difference of Median[95% CI]"), slab=dat.age$author, xlab="Difference of Median age (years)")
> text(-23, -1, pos=1, cex=0.7, bquote(paste("Heterogeneity: Q = ",.(formatC(abc$QE, digits=2, format="f")), ", df = ", .(abc$k - abc$p),", p = ", .(formatC(abc$QEp, digits=2, format="f")), "; ", I^2, " = ",.(formatC(abc$I2, digits=1, format="f")), "%", "; ", tau^2 == .(formatC(abc$tau2, digits=2, format="f")))))

![image](https://github.com/stmcg/metamedian/assets/143593753/5f493d32-54ef-4041-a6ba-ebb8843077cb)

Within the forest plot I would like to present:

**Numbers:**

- the first quartile, median, third quartile, number of participants and weight of each treatment within each study presented in the forest plot. 

**Labels:**

- Place label over the upper part of the forest plot stating Difference of median, Random, 95%CI
- Have heterogeneity parameters in the lower left segment that do not move sideways when I resize the forest plot
- Insert test for overall effect and its p-value

**Style:**

- Making it in Revman style
- Swapping the difference in median(95%CI) and the forestplot, so that the heterogeneity parameters do not clash with the vertical line. 

Is there a way to include the above features within the forest plot?

Thank you

Emanuel

**Comment by stmcg** [comment]
Hi Emanuel,

Thanks for posting. 

The `forest` function applied to the output of the `metamedian` is actually from the **metafor** package. I think the help file for the `metafor::forest.rma` function would address most of these (eg, including additional columns with the reported summary statistics via the `ilab` argument). 

Alternatively, is there another package for making forest plots that you are more familiar with? If so, you could extract all of the study-specific outcome measure estimates and their sampling variances from `abc`, and then feed that information to your preferred package/software.

Best,
Sean
