### ISSUE TITLE
Subgroup analysis in metamedian

### ISSUE THREAD

**Issue by Emanuel-1986** [stmcg/metamedian#4]
Hi,

Is there a way to conduct subgroup analysis and illustrate the two (or more) subgroup pooled effects in metamedian? E.g subgrouping by treatment subtype or by the risk of bias grade?

Thanks

Emanuel

**Comment by stmcg** [comment]
Hi Emanuel,

I think the easiest way to do this would be to just provide an input data set with studies comprising your subgroup of interest, repeating the analysis for each subgroup. Does that make sense? Or am I missing something?

Best,
Sean

**Comment by Emanuel-1986** [comment]
Dear Sean,
Thank you for your prompt response. 
I can do it the way that you suggested, but i would like to have the Chi square test of differences between the subgroups and ideally illustrate the subgroups in the forest plot too, just like a typical forestplot. 
Regards 
Emanuel

**Comment by stmcg** [comment]
Oh I see. I'm assuming you're using one of the methods that performs an inverse-variance weighted meta-analysis. Ultimately, those approaches in the `metamedian` package apply the `metafor` package for the pooling (after estimating the study-specific outcome measures and their standard errors). Heads up that the output of the `metafor` package is returned by the `metamedian` package, and you can supply any additional arguments to the `rma` function in the `metafor` through the `metamean` and `metamedian` functions in the `metamedian` package.

So performing tests and forest plots based on subgroups ultimately comes down to functionality in the `metafor` package. Here are some links on testing for differences between subgroups (eg, https://www.metafor-project.org/doku.php/tips:comp_two_independent_estimates) and forest plots with subgroups (eg, https://www.metafor-project.org/doku.php/plots:forest_plot_with_subgroups).

It looks like the `meta` package may have some more options for testing difference between subgroups. So another option would be to extract the study-specific estimates and standard errors from the output of the `metamedian` package and then perform the pooling and subsequent subgroup tests, etc in the `meta` package

**Comment by Emanuel-1986** [comment]
Hi Sean,

Yes, I intend to apply an inverse-variance weighted meta-analysis, specifically the QE method, as stated in your paper on Metamedian. 

Thank you for informing me that I can supply additional arguments to the rma function through the Metamedian package. 

- How can I extract both the study-specific estimates and standard errors from the output of the Metamedian package?

Kind regards,

Emanuel

**Comment by stmcg** [comment]
If you set `pool_studies = FALSE` in the `metamedian` function, the study-specific estimates are in the `yi` component and the study-specific standard errors are in the `sei` component of the output

**Comment by Emanuel-1986** [comment]
Dear Sean,
Thank you for your response.
Much appreciated. 
Best regards,
Emanuel
